### ISSUE TITLE
Run Module on Raspberry Pi 3

### ISSUE THREAD

**Issue by gbbiotwesouth** [Azure/iot-edge-opc-publisher#109]
When deploying the module to a Raspberry Pi 3 installation of the IoT Edge, the module fails with error: ' standard_init_linux.go:195: exec user process caused "exec format error"'  and keeps on reloading.

**Comment by gbbiotwesouth** [comment]
I see the size of the module is 1.89Gb on the Raspberry, which will not work with the memory available. Will you build a linux-arm32 version with limited size? As was done with the modbus module.

**Comment by Eichi87** [comment]
I'm running in the same error. Is there any workaround?
