### ISSUE TITLE
Feature request: Support of http-proxy by opc publisher

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-publisher#117]
Hello,

for some networks with restrictive firewall policies, we need the feature, that the OPC Publisher connects to the IoT-hub through an http-proxy with authentication.
In a similar way as it is implemented for the iot-edge-opc-proxy (see https://github.com/Azure/iot-edge-opc-proxy/issues/14 ).

Greetings
Juergen

**Comment by marcschier** [comment]
IoT Edge now contains support for web proxy:  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support.   Closing.
