### ISSUE TITLE
OPC not connecting

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/iot-edge-opc-publisher#122]
I have the module up and running in edge and on the same server I am running Kepware as a host process.

If I configure the Edge OPC module to talk to 10.0.75.1 it reports 1 OPC session but NO connected session.
Kepware OPC config is set to run the OPC server on 10.0.75.1

I see the following in the logs for the module:

```
06/14/2018 17:52:13: Connect and monitor session and nodes on endpoint 'opc.tcp://10.0.75.1:49320/'.
06/14/2018 17:52:13: Create unsecured session for endpoint URI 'opc.tcp://10.0.75.1:49320/' with timeout of 50000 ms.
06/14/2018 17:52:14: Session creation to endpoint 'opc.tcp://10.0.75.1:49320/' failed 8 time(s). Please verify if server is up and Publisher configuration is correct.
06/14/2018 17:52:14: Endpoint does not supported the user identity type provided.
```

published nodes JSON:

```
[
  {
    "EndpointUrl": "opc.tcp://10.0.75.1:49320",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "ExpandedNodeId": "nsu=KEPServerEX;s=Channel1.F1_DEV:230106.AnalogInput_12.PresentValue"
      },
      {
        "ExpandedNodeId": "nsu=KEPServerEX;s=Channel1.F1_DEV:230107.AnalogInput_54.PresentValue"
      },
      {
        "ExpandedNodeId": "nsu=KEPServerEX;s=Channel1.F1_DEV:230109.AnalogInput_56.PresentValue"
      }
    ]
  }
]
```

Kepware configured to allow "None" for security policies

Thanks,
Dave

**Comment by hansgschossmann** [comment]
Does the KepWare OPC server requires any user authentication or does it allow anonymous user access?

**Comment by hansgschossmann** [comment]
No response. Closing. Please reopen if required.

**Comment by jmbrunskill** [comment]
Just in case it helps someone, thought I'd add a comment here. To configure KEPServer for anonymous user access via OPC UA you need to open the kepserver configuration tool, right click on the top level 'project' and go to properties. Under this dialog you should find a tab called OPC UA. Open this and set 'Allow anonymous login' to 'Yes'
![image](https://user-images.githubusercontent.com/8287373/51583240-8adcd700-1f34-11e9-82b7-f72aa09c69ed.png)

**Comment by SachaLhopital** [comment]
Many thanks @jmbrunskill ! You helped me very much with this ! 

🎉  🎉 !
