### ISSUE TITLE
Can not publisher certificate to trusted peer store

### ISSUE THREAD

**Issue by Norman03** [Azure/iot-edge-opc-publisher#125]
![warning](https://user-images.githubusercontent.com/41000195/42448833-230c8974-839c-11e8-88b9-bf7f08f06bb9.PNG)

Can anyone post the steps to run OPC Publisher in windows? @barnstee @hansgschossmann @marcschier @sebader @mregen @rangedsp

**Comment by sebader** [comment]
It says the certificate is already in store - probably from a previous run of the program. So you should be able to ignore that error. Does it run on from that or stop there?

**Comment by Norman03** [comment]
Thanks! @sebader 
This is the command we used to solve this issue 
`dotnet OpcPublisher.dll <application-name> <connectionstring>`
Use the connectionstring without double quotes. Closing this issue.
