### ISSUE TITLE
docker images have stopped getting specific tags

### ISSUE THREAD

**Issue by damienpontifex** [Azure/iot-edge-opc-publisher#141]
We were looking at selecting a version of this image (avoid unexpected future changes) but noticed that the [tags on docker hub](
https://hub.docker.com/r/microsoft/iot-edge-opc-publisher/tags) are just being pushed as latest. i.e. no specific version tags since 7 months ago.

Is this intentional and could it be possible to adopt a semver style so we could utilise the latest images while still getting pinned versions?

Also, thanks for the great module! Saved a lot of time

**Comment by hansgschossmann** [comment]
there have been new tags now and there will be more in the future. the images are now available via Microsoft Container Registry. the tags can be found at https://hub.docker.com/r/microsoft/iot-edge-opc-publisher/
