### ISSUE TITLE
Error when settings properties for IoTEdge module

### ISSUE THREAD

**Issue by eoursel** [Azure/iot-edge-opc-publisher#143]
Looks like the container create options is too long when using the Azure portal wizard. At least if i add something i will exceed the 512 bytes limit. 

BadRequest:{ "Message": "ErrorCode:ArgumentInvalid;Property or Tag value should be maximum 512 bytes.`

**Comment by manuelfuchs** [comment]
You can save a few bytes by removing the tabs/spaces from your CreationOptions JSON.
I know it's not a fix but this removed just enough characters for me to solve this issue.

**Comment by sandervandevelde** [comment]
I had the same issue. With the recent 1.0.4 release of IoT Edge runtime/modules this should be fixed (size is [now limited to 4K](https://azure.microsoft.com/en-us/updates/iot-edge1-0-4/)).

See also https://github.com/Azure/iotedge/commit/ecfc2a0d30edced286c42d5090bd9eb953251b86

**Comment by hansgschossmann** [comment]
@sandervandevelde thanks for pointing this out. i have not verified it. i will also add an option to change the root directory of the certstore, then there is no need to specify locations for each store (trusted, rejected,..) separately.
I will follow-up with the portal team if they can change it to compress the JSON entered in the portal before they check the size.
