### ISSUE TITLE
Let configuration be maintaned from Azure IoT Edge module Twin

### ISSUE THREAD

**Issue by FluxReality** [Azure/iot-edge-opc-publisher#144]
Create an option to read **PUBLISHEDNODES.JSON** and **TELEMETRYCONFIGURATION.JSON** from the Azure IOT Edge module twin on Azure IOT Hub.

Also there should be an option to retrieve certificates from the Azure Key Vault.

Makes managing remote devices much simpler.

**Comment by sandervandevelde** [comment]
Adding the feature to use the ModuleTwin is appreciated. This would make the OPCPublisher module much more flexible! Then we can update the module without changes on the Edge device file system.

**Comment by hansgschossmann** [comment]
for version 2.2+ i have added direct methods to configure the nodes. see https://github.com/Azure-Samples/iot-edge-opc-publisher-nodeconfiguration for a sample to use it. 
for the telemetryconfiguration.json i have not yet something implemented. thanks for the idea.

**Comment by FluxReality** [comment]
@hansgschossmann Thanks for the update.

I still think it would be better if the configuration was read through the Module Twin than direct methods. This because Direct Method requires multiple extra steps upon deployment, whereas Twin parameters, can be handled by deployment-manifests.

Also direct methods, requires the device to be connected at the time of configuration, which might not always be the case. 

My request still stands.

**Comment by hansgschossmann** [comment]
the problem is that there are size limitations in the twin properties, which would give you a hard limit on the number of nodes you can publish. thoughtsß

have you checked out the repo https://github.com/Azure-Samples/iot-edge-opc-publisher-nodeconfiguration this is even simpler than configure it via the portal.

**Comment by sandervandevelde** [comment]
Regarding the PUBLISHEDNODES.JSON, is the URL also configurable using Create options or direct methods?

**Comment by FluxReality** [comment]
@hansgschossmann I see this limitation, and understand that there are [plans](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/33933409-increase-512-byte-limit-for-create-container-optio?tracking_code=8150baf35d8cd14ebc9641864b342c3a) for increasing this limit.

When I created my own OPCua publisher module using python and [FreeOpcUa](https://github.com/FreeOpcUa/python-opcua), I set the basic configurations in the Module Twin, and the node configuration is being read from a Azure File-store, indicated to by a twin property (this could also be a CosmosDB document)

Maybe not ideal, but it makes the whole deployment much simpler and flexible.

**Comment by sandervandevelde** [comment]
Using blob storage would do well for our projects. This is exactly the same way that the Azure Stream Analytics team deploys their query/inputs/outputs.
