### ISSUE TITLE
IotEdge Agent not able to deploy specified module 'Error calling Create module iot-edge-opc-publisher: Container runtime error'

### ISSUE THREAD

**Issue by manuelfuchs** [Azure/iot-edge-opc-publisher#147]
I declared the iot-edge-opc-publisher module just like declared in the tutorial, but when the agent on the edge device tries to deploy the module. the agent gets a exception.

![log](https://user-images.githubusercontent.com/13959511/44262862-d8824480-a21c-11e8-80b5-8879f699f7a8.PNG)

I declared the module via the 'Set Modules' in the IoT Hub for this specific edge device and the edge device is a azure windows 10 virtual machine.

This were my container creation options ...
![json](https://user-images.githubusercontent.com/13959511/44262763-79243480-a21c-11e8-8435-aa27c2038159.PNG)
... first and then tried exactly yours from the instructions, neither did work.

**Comment by hansgschossmann** [comment]
I have updated the documentation for use with the GA version of IoT Edge a few weeks ago. Can you please retry with those?

**Comment by swapshahir** [comment]
I am facing same issue while deploying OPC publisher as module in azure IOT edge. Is there any solution for this?

**Comment by hansgschossmann** [comment]
This should work without issues with the updated documentation and latest IoT Edge. There are now OPC Publisher containers available for Windows/AMD64 and Linux/ARM as well. Pls reopen if you still see an issue.
