### ISSUE TITLE
Publishednodes.json "UseSecurity=false" not working  

### ISSUE THREAD

**Issue by merlingeorge555** [Azure/iot-edge-opc-publisher#150]
In Publishednodes.json "UseSecurity=false" line is deleted automatically after the docker build and run. I have tried setting read access only to the Publishednodes.json file. Even then UseSecurity is missing. If its true the line is not deleted. Why is that so?

**Comment by sandervandevelde** [comment]
I got it working with ""UseSecurity": false,". This is valid JSON.

**Comment by hansgschossmann** [comment]
As @sandervandevelde (thanks) pointed out your example is invalid JSON. 

The default for UseSecurity is true and for this reason it is not kept in the .JSON file. If you set it to false, then it is kept.
