### ISSUE TITLE
What about implementing additional IoTHub direct methods for writing values to OPC nodes?

### ISSUE THREAD

**Issue by anhame** [Azure/iot-edge-opc-publisher#152]
This could help to avoid the need for implementing a separate OPC UA client application for writing values to the OPC server(s).
best

**Comment by hansgschossmann** [comment]
This is a good idea, but beyond the functionality of OPC Publisher. Please check out: https://github.com/Azure/azure-iiot-opc-twin-service which allows you to use read/write/browse functionality and will be expanded with more features moving forward. This comes with a microservice, which can be used via its REST API.

Another option which allowed to use full OPC UA functionality is https://github.com/Azure/iot-edge-opc-proxy
This requires modification of the OPC UA transport as we showcased in Connected Factory: https://github.com/Azure/azure-iot-connected-factory
