### ISSUE TITLE
publishednodes.json does not exist

### ISSUE THREAD

**Issue by ak5h2y** [Azure/iot-edge-opc-publisher#156]
[command_prompt.txt](https://github.com/Azure/iot-edge-opc-publisher/files/2478255/command_prompt.txt)

I had cloned the iot-edge-opc-publisher into C:/ and named the directory as 'app'

I have my docker in windows container mode.

I replaced the Dockerfile in root directory with the Dockerfile for windows.
-> Build the docker for a container 15oct18

When I tried to run the container with an application, towards the end I receive a message that "publishednodes.json does not exist" and the Publisher exits.

Objective: to have two containers on my win10 PC & visualize the OPC UA communication between them, thereafter replace one of them with RaspberryPI.

Kindly support.
Thank you in advance.

**Comment by hansgschossmann** [comment]
I do not understand why you are using OPC Publisher "to have two containers on my win10 PC & visualize the OPC UA communication between them"

To play around, you may also want to have a look into this repo: https://github.com/Azure-Samples/iot-edge-industrial-configs

If you still want to use it, there are prebuilt containers available in the Microsoft Container Registry. Check out the available tags at: https://hub.docker.

Please reopen the bug if you still have OPC Publisher specific questions.
