### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by ggokka** [Azure/iot-edge-opc-publisher#161]
>docker build -t azure_opc_pub https://github.com/Azure/iot-edge-opc-publisher
Sending build context to Docker daemon  145.4kBs://github.com/Azure/iot-edge-opc-publisher  143.8kB
Error response from daemon: Dockerfile parse error line 7: unknown instruction: <!DOCTYPE

**Comment by hansgschossmann** [comment]
Use: docker build -t azure_opc_pub https://github.com/Azure/iot-edge-opc-publisher.git
