### ISSUE TITLE
Publish all nodes of a given OPC UA Server

### ISSUE THREAD

**Issue by Eichi87** [Azure/iot-edge-opc-publisher#174]
Is it possible to publish all available nodes of a OPC UA Server?

Right now I add every nodeID to the pblishednodes.json document.
```
[
  {
    "EndpointUrl": "opc.tcp://blueface:48010",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "Id": "ns=6;s=AirConditionerXml.Humidity",
        "OpcSamplingInterval": 2000,
        "OpcPublishingInterval": 5000
      },
      {
        "Id": "ns=6;s=AirConditionerXml.Temperature",
        "OpcSamplingInterval": 2000,
        "OpcPublishingInterval": 5000
      }
    ]
  }
]
```

I tried `"Id": "ns=6;s=AirConditionerXml` but this doesn't seem to work.

The thing is, I want the OPC publisher to publish newly added objects without the need to edit publishednodes.json and restart the server.
A workaround could be to update the published nodes while the publisher is running. That way I could use another tool to automatically update the node list. Is this possible somehow?

Thanks in advance
Daniel

**Comment by hansgschossmann** [comment]
How about using OPC Publisher direct method calls? See https://github.com/Azure-Samples/iot-edge-opc-publisher-nodeconfiguration for a tool and/or sample code.

**Comment by hansgschossmann** [comment]
Another option would be to extend the [Xamarin client which is available in the OPC Foundation repository](https://github.com/OPCFoundation/UA-.NETStandard/blob/master/SampleApplications/Samples/XamarinClient/readme.md). This tool already allows browsing an OPC UA server). A nice extension would be to communicate with OPC Publisher to configure it to publish nodes.

**Comment by Eichi87** [comment]
The nodeconfiguration tool works just fine. Thank you very much.

But I'm still curious if it's possible to publish all properties and components below a node.
For example there is a node "Fluid temperature" (ns=2;s=11000.Density) which has several properties and components like identification and unit. (...Density.Identification and .Unit). If I want to publish them, I need to add every single nodeID. Right now, I don't know if there is a way to publish a node with every subordinate node, short of programming a new tool which uses the nodeconfiguration tool.

**Comment by Eichi87** [comment]
Problem is solved. Here's what we did: When building an OPC UA server we also build a publishednodes.json. After connection to the publisher machine was established through simple tcp connectivity, the publisher machine downloads publishednodes.json from the OPC UA server machine and runs https://github.com/Azure-Samples/iot-edge-opc-publisher-nodeconfiguration. Not exactly what we were planning to do but in the end all we needed. Thanks again.
