### ISSUE TITLE
OPC Publisher not reconnecting after edgeHub crash

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iot-edge-opc-publisher#188]
After edgeHub crashes and recovers, the OPC Publisher looses it's connection to edgeHub.  No Messages are received in edgeHub anymore.

We route the messages send by OPC Publisher through some custom modules which generate messages to be send to IotHub.  After a crash of edgeHub the custom modules do not receive messages from OPC Publisher anymore.  After "sudo docker stop publisher"  the OPC Publisher module recovers and starts sending messages again.

**Comment by BewaControl-ReneDivossen** [comment]
With the latest release and using AMQP it's just the other way around. 
If I kill the edgeHub module using "docker stop" everything will recover nicely but if I kill the publisher module using "docker stop" it will not send messages anymore after coming up running again.

**Comment by BewaControl-ReneDivossen** [comment]
For AMQP everything is working after this [commit](https://github.com/Azure/iot-edge-opc-publisher/commit/8f1d85f284bc9891b97eb7e683ad00ed3816072f)

**Comment by hansgschossmann** [comment]
fixed with 2.3.3
