### ISSUE TITLE
Raw AMQP Publishing

### ISSUE THREAD

**Issue by clemensv** [Azure/iot-edge-opc-publisher#200]
The publisher should be able to send to any AMQP endpoint, in addition to IoT Hub. 

Here's a fork off Hans' UT branch that enables AMQP as a hack. The real code path should be a clone of the core of the Event Hub send path, including retry policy, except that it's using SASL PLAIN instead of CBS.

https://github.com/clemensv/iot-edge-opc-publisher

**Comment by markusstuhler** [comment]
Hi @clemensv, this is currently not on our roadmap to support, but we are working on some refactorings that will allow to easily replace transportation layer. However, we have no timeline for this yet.
