### ISSUE TITLE
Reading History Data 

### ISSUE THREAD

**Issue by djdtimit** [Azure/iot-edge-opc-publisher#219]
Hey,

is it possible to read historical data via the OPCPublisher from OPC UA servers (readHistory property of the OPC specification)? 

If not, are there plans to implement this feature? And what is the preferred way to read historical data and send the data to an IoT hub in this case?

Thanks in advance.

**Comment by marcschier** [comment]
Hi @djdtimit . You can use the OPC History micro service in conjunction with our OPC Twin module (https://github.com/Azure/azure-iiot-components) to read historic data.   It is currently in pre-release, and functionality is limited to reading historic values, not events.  All your reads are synchronous, i.e. you are using the API to query the historian.  We are thinking about adding asynchronous trigger to upload to blob functionality down the road, feel free to provide feedback, file bugs, or request this and other functionality through the issues tab at https://github.com/Azure/azure-iiot-components.
