### ISSUE TITLE
BadSubscriptionIdInvalid for nodes with SamplingInterval of 100ms

### ISSUE THREAD

**Issue by dcrupel** [Azure/iot-edge-opc-publisher#221]
Hi,

![badsubid](https://user-images.githubusercontent.com/35105327/55308940-7f3ded00-545c-11e9-97e5-d00fde47530a.png)

After running without problems for months the publisher stops monitoring the Tags with a sampling interval of 100ms, the ones with sampling interval of 1000ms keep coming in.

So, the subscription of the 100ms nodes is stopped, the other one (1000ms sampling interval) remains.

Any idea how to prevent this from happening? 

Thanks!

Regards

**Comment by markusstuhler** [comment]
Hi @dcrupel,  we'll look into this.

**Comment by markusstuhler** [comment]
Hi @dcrupel, could you share which version of the publisher you were using? Did you update at some point in time? Are there any other things that changed?

**Comment by krenting** [comment]
Hi @dcrupel,

I had this same problem but only when i connected to the machine via middleware (Kepware). When connected to the machine directly i could use sample rates of 50ms without any problems. Have you done some testing with different OPC UA servers?

Regards

**Comment by krenting** [comment]
Hi @dcrupel,

I had this same problem but only when i connected to the machine via middleware (Kepware). When connected to the machine directly i could use sample rates of 50ms without any problems. Have you done some testing with different OPC UA servers?

Regards

**Comment by krenting** [comment]
Hi @dcrupel,

I had this same problem but only when i connected to the machine via middleware (Kepware). When connected to the machine directly i could use sample rates of 50ms without any problems. Have you done some testing with different OPC UA servers?

Regards

**Comment by krenting** [comment]
Hi @dcrupel,

I had this same problem but only when i connected to the machine via middleware (Kepware). When connected to the machine directly i could use sample rates of 50ms without any problems. Have you done some testing with different OPC UA servers?

Regards

**Comment by dcrupel** [comment]
Yes, It is a Kepware problem so this has nothing to do with the OPC publisher. I'll close this issue.

**Comment by krenting** [comment]
I'm in contact with the developers of Kepware on this issue. If there is any progress I'll send you an update.
