### ISSUE TITLE
Update to latest IotHubSDK

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iot-edge-opc-publisher#229]
Can you please update to the latest IotHubSDK.
There have been some fixes that should make AMQP more stable and should allow reconnecting after failure.

Versions:
Microsoft.Azure.Devices 1.17.3
Microsoft.Azure.Devices.Client 1.20.0

**Comment by BewaControl-ReneDivossen** [comment]
@hansgschossmann - Any timeline on this ?

**Comment by hansgschossmann** [comment]
@markusstuhler - do you already know when we are going to update?

**Comment by markusstuhler** [comment]
This will be part of the 2.3.7 release which we aim to release by the end of this month.

**Comment by BewaControl-ReneDivossen** [comment]
@markusstuhler - does "end of this month" mean today ?  Or are you in some part of the world where it is already Mai 1st ?

**Comment by markusstuhler** [comment]
My mind was already in the next sprint ;) So I meant end of May.

**Comment by BewaControl-ReneDivossen** [comment]
OK. Thanks for clarification.  
I'll be waiting for the release.

**Comment by BewaControl-ReneDivossen** [comment]
@markusstuhler - I've seen that you updated the IotHub SDK in the repository.
I'm sorry to be bothering you again but version 1.20.0 is already deprecated again.
There now is 
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.20.1" /> 
That's the version they have used in the 1.0.7 release of IotEdge that was released a couple of days ago.

**Comment by BewaControl-ReneDivossen** [comment]
Version 1.20.2 is out now and should be referenced.

**Comment by marcschier** [comment]
2.4.x is using the latest 1.21.
