### ISSUE TITLE
Does Heartbeat use KeepAlive-Notifications of the OPC-Server?

### ISSUE THREAD

**Issue by mma-mm** [Azure/iot-edge-opc-publisher#237]
Hi,

i'd like to use the heartbeat feature of the publisher. Does the publisher set a time for heartbeat itself, or does it use some opc feature to get notified by the server, that nothing has changed for a while?

Background: 
We need to make sure that the values that are transmitted in heartbeat style actually come from the opc-server.

Best regards
Matthias

**Comment by markusstuhler** [comment]
The publisher is sending the last value with an updated timestamp as heartbeat (from cache, not by reading it again). It's not using any OPC UA server feature.

Thanks!
Markus
