### ISSUE TITLE
How do I build this as an edge module project in VS Code?

### ISSUE THREAD

**Issue by btmmf** [Azure/iot-edge-opc-publisher#243]
I successfully followed [Tutorial: Develop IoT Edge modules for Linux devices](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux) from the Azure IoT Edge Documentation, including building, pushing and deploying an edge module to a device using Visual Studio Code.

Now I am trying to to apply this knowledge to the OPC Publisher.
Sadly, the wiki only explains how to build this project [As native Windows application](https://github.com/Azure/iot-edge-opc-publisher#as-native-windows-application) and [As Docker container](https://github.com/Azure/iot-edge-opc-publisher#as-docker-container).
While the process of building and deploying the edge module certainly requires a container to be created, merely creating a docker container is not enough. Or is it?

The entire project structure is different, because the OPC Publisher is a Visual Studio ~Code~ 2017 project, with a solution file and all that jazz.
How do I transform it into a project where I can build and deploy the module from a **deployment.template.json** file like in the tutorial?

![image](https://user-images.githubusercontent.com/51480932/61306071-3aac4680-a7ec-11e9-80bc-c6b19ff8a53c.png)

PS: I found [Using it as a module in Azure IoT Edge](https://github.com/Azure/iot-edge-opc-publisher#using-it-as-a-module-in-azure-iot-edge), but I do not want to deploy it as a module, I want to modify the code like in the tutorial.

Thank you for your help.

**Comment by marcschier** [comment]
A docker container is all that is needed to run the publisher as part of IoT Edge.   

The project file in the repo does not use the IoT Edge VS extension.   

However, the docs show a sample module deployment manifest, which you can use to deploy opc publisher into IoT Edge instance, e.g. using the instructions here:  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-modules-cli.   

The repo also includes a "debug" dockerfile that allows you to build a container with remote debugger included, to debug a running instance inside IoT Edge.
