### ISSUE TITLE
OpcUaSession.Read/Write methods removed?

### ISSUE THREAD

**Issue by anhame** [Azure/iot-edge-opc-publisher#247]
Hello,
in version 2.3.3 of the opc publisher, there were two methods available in OpcUaSession allowing to read and write multiple nodes. I used these methods for implementing some own extensions. In version 2.4.1 these functions have been removed. Would it be possible to make them available again?

best regards
Hartmut

**Comment by markusstuhler** [comment]
Hi @anhame 
we discussed adding "Write" back, but we decided that we do not want to support this functionality in OPC Publisher because it's never needed. However, if you want to write values to nodes, you can use the OPC stack, which is also used by the publisher.

Thanks!
Markus
