### ISSUE TITLE
Limit publishednodes

### ISSUE THREAD

**Issue by richterr** [Azure/iot-edge-opc-publisher#250]
### Issue
After generating a publishednodes.json with >1500 configured tags to monitor I get the following Error Message.

![image](https://user-images.githubusercontent.com/42353719/62116708-ebb9e300-b2ba-11e9-846f-141a320fd1a4.png)

After shortening the list to ~700 tags the error disappears.
What is the limit for the monitored tags? Is it a limitation of the OPC UA Server or the OPC Publisher?

Thanks in advance.

### Environment
Ubuntu 18.04 LTS
OPC Publisher (2.3) in IoT Edge Runtime (1.0.7)

**Comment by markusstuhler** [comment]
Hi @richterr, this error message is coming from the OPC UA Server, not from the publisher.

May I ask which server you are using?

Thanks!
Markus

**Comment by richterr** [comment]
So there is no limit for tags in the publishednodes.json file?
We are running the OPCPublisher against a Siemens S7-1500 with OPC UA Server activated. What causes this kind of error on the OPC UA Server? Is it a performance restriction or some misconfiguration on the server side?
Thanks in advance.

**Comment by markusstuhler** [comment]
We're no S7 experts, but it looks like a configuration setting in the S7 or it hits limits what the server can support. Please check the documentation of the server on how many items are supported.

Thanks!
Markus

**Comment by richterr** [comment]
Alright, thanks a lot.
