### ISSUE TITLE
opc publisher error

### ISSUE THREAD

**Issue by bellenkurt** [Azure/iot-edge-opc-publisher#275]
Hello we get this error in the output of our opc module

[16:09:03 VRB] OPC: Bytes written: 106
[16:09:03 DBG]    ApplicationUri: urn:BEHQWINFTPRD01:FactoryTalk Linx Gateway OPC UA Server
[16:09:03 DBG]    EndpointUrl: opc.tcp://behqwinftprd01:4990/behqwinftprd01
[16:09:03 DBG]    DisplayName: ns=3;s=DS/RSLE::[PWM002]F21:2
[16:09:03 VRB] OPC: PUBLISH #208 SENT
[16:09:03 DBG]    Value: 458.367676
[16:09:03 DBG] Enqueue a new message from subscription 3428698689
[16:09:03 DBG]  with publishing interval: 0 and sampling interval: 1000):
[16:09:03 ERR] Error processing monitored item notification
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpcPublisher.OpcMonitoredItem.MonitoredItemNotificationEventHandler(MonitoredItem monitoredItem, MonitoredItemNotificationEventArgs e) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcMonitoredItem.cs:line 566

this is the config of the container create options

{
    "Hostname": "publisher",
    "Cmd": [
        "--pf=/appdata/publishednodes.json",
        "--aa",
        "--ms=0",
        "--si=10",
        "--ll=verbose"
    ],
    "HostConfig": {
        "Binds": [
            "c:/iiotedge:c:/appdata"
        ]
    }
}

this is the config of hte publishednodes.json

[
  {
    "EndpointUrl": "opc.tcp://behqwinftprd01:4990/behqwinftprd01",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "Id": "ns=3;s=DS/RSLE::[PWM002]F21:2"
      }
    ]
  }
]

does anyone has any idea why we get this error

**Comment by barnstee** [comment]
Note: This happens with OPC Publisher 2.5.4.

**Comment by bellenkurt** [comment]
what version should we the run, and can you maybe give us the command line to configure this; this is the command line we run now for the current module

mcr.microsoft.com/iotedge/opc-publisher:latest

**Comment by bellenkurt** [comment]
> Note: This happens with OPC Publisher 2.5.4.

what version should we the run, and can you maybe give us the command line to configure this; this is the command line we run now for the current module

mcr.microsoft.com/iotedge/opc-publisher:latest

**Comment by barnstee** [comment]
Please use 2.5.3-debug and send me the new verbose log, please.

**Comment by bellenkurt** [comment]
mcr.microsoft.com/iotedge/opc-publisher:2.5.3-debug

like this?

**Comment by barnstee** [comment]
yep

**Comment by bellenkurt** [comment]
[publishlog.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5608465/publishlog.txt)
this is the updated log with version 2.5.3 => i still see that error

**Comment by barnstee** [comment]
With the debug output, we could analyze the issue and it is a rare race condition in the OPC Publisher, which we fixed in subsequent versions. Please try version 2.7.199-debug.

**Comment by barnstee** [comment]
Also, in some cases, the error is fixed by restarting IoT Edge. Please try this before going to version 2.7.

**Comment by bellenkurt** [comment]
hello Erich

thank you very much for the help, this solved the issue; just a reboot and restart from the publisher module on the edge device together with the 2.5.3-debug version

thx
kurt

**Comment by barnstee** [comment]
Ok, good. For performance, feel free to switch back to an optimized/release build, i.e. without the -debug.
