### ISSUE TITLE
Could not pull image of OPC publisher module version 2.5.4

### ISSUE THREAD

**Issue by SandeepThombare** [Azure/iot-edge-opc-publisher#279]
Hi,

I am trying to deploy the Opc publisher module 2.5.4 version to IoT Edge but getting error and module is not getting created in IoT edge

please see below log of edgeAgent module,
![2 5 4 error](https://user-images.githubusercontent.com/71124513/100740939-7d7db700-33ff-11eb-8be5-03d175fd9a25.JPG)

If i use version 2.5.3, it is working fine and I am able to use opc publisher module version 2.5.3 on Edge device.

**Comment by monikavar** [comment]
The changes are in 2.5.3 and 2.5.4 is no longer necessary and has been removed.
