### ISSUE TITLE
error "Could not send worker heartbeat"

### ISSUE THREAD

**Issue by franperezlopez** [Azure/iot-edge-opc-publisher#280]
Hi,

I've just update my iotedge module, which is built using the image mcr.microsoft.com/iotedge/opc-publisher:latest, and when is deployed in the iotedge device, start failing and doesn't collect any data ... is there any change I need to be aware??

![image](https://user-images.githubusercontent.com/1222398/100746043-78f5d600-33e0-11eb-9bd3-b22ab24b4f91.png)

**Comment by monikavar** [comment]
What is the setup and which version of the OPC Publisher were you using before?

Additionally, are you using industrial IoT microservices?

**Comment by barnstee** [comment]
Please get back to our question, or is the issue resolved?

**Comment by barnstee** [comment]
@franperezlopez

**Comment by franperezlopez** [comment]
Sorry for the late response,

a) I did additional tests, and the problem seems not related to the opcpublisher version. There is a telegraf module (docker) for ingesting data from opcserver directly to influxdb, and I get this error when opcpublisher and telegraf are working at the same time. if opc publisher is working alone, it works fine
b) I don't know what you mean by Industrial IoT microservices ... how can I check that?

**Comment by barnstee** [comment]
@franperezlopez , if you are not using industrial IoT services, it explains the error: The worker heartbeat is something the OPC Publisher is trying to send to the industrial IoT services. If you are using a publishesnodes.json file, the OPC Publisher should automatically switch to standalone more, not requiring the industrial IoT services. Do you have one configured?
Not sure how the telegraph modules is affecting this, it shouldn't as each module is running in its own container.

**Comment by franperezlopez** [comment]
there was an error in the configuration of the deployment template, so no configuration file was set. a little bit "bizarre" that because the json file is missing, I get an error of the heartbeat, a warning message would have been more helpful .. but whatever, now is working. thanks for your support

**Comment by sagarganachari** [comment]
> there was an error in the configuration of the deployment template, so no configuration file was set. a little bit "bizarre" that because the json file is missing, I get an error of the heartbeat, a warning message would have been more helpful .. but whatever, now is working. thanks for your support

How did you resolve this issue @franperezlopez 

https://github.com/Azure/Industrial-IoT/issues/993

**Comment by franperezlopez** [comment]
@sagarganachari  .. this error was provoked by a typo in my deployment template. 

check your published docker in the iotedge device, then open a bash terminal into the running docker (`docker exec ... bash`), and check that the configuration file which you provide as `createOptions` (for example, `--pf=/app/opcserver.json` or whatever you have) actually exists.

**Comment by sagarganachari** [comment]
> pen a bash terminal into the running docker

@franperezlopez  i checked container option path /app/publishenodes.json exists in linux edge device.

iotedge status showing OPCPublisher running.....
![image](https://user-images.githubusercontent.com/76048188/103534631-28621480-4e87-11eb-9a6d-da3d6cc96c1d.png)

**Comment by franperezlopez** [comment]
in my case, it didn't matter .. the opc publisher might be running, but the config file might be missing ... as I said in my comments before, the opc publisher does not display an error message if the config file is missing. 

if you say that the config file it is on the edge device, that means that you need to bind that volume to the docker, right? again, open a bash console against the running opcpublisher, and check that you can execute a command like `ls /app/publishenodes.json` to make sure opcpublisher has access to the config file. otherwise, you're hitting a different problem that was mine.

**Comment by sagarganachari** [comment]
@franperezlopez @monikavar 

Unfortunately yes i am hitting a different problem

after executing the command i am accessing the path...find screen shot

![image](https://user-images.githubusercontent.com/76048188/103536550-a542bd80-4e8a-11eb-84b7-7b6516225da1.png)

**Comment by barnstee** [comment]
You just ran that command on the host, you need to run the command *within* the container. That's what @franperezlopez meant with "against the container".

**Comment by sagarganachari** [comment]
> You just ran that command on the host, you need to run the command _within_ the container. That's what @franperezlopez meant with "against the container".
@barnstee 

Yes i ran it within container i am getting ls: cannot access /app/publishenodes.json, attached screen shot

![image](https://user-images.githubusercontent.com/76048188/103541907-07ec8700-4e94-11eb-92e9-51396471e0dc.png)

**Comment by barnstee** [comment]
"No such file or directory" -> There's your problem! Please check the directory mapping to the host.

**Comment by sagarganachari** [comment]
![image](https://user-images.githubusercontent.com/76048188/103542977-ae855780-4e95-11eb-85d6-43d42895c9f7.png)
![image](https://user-images.githubusercontent.com/76048188/103543073-d4aaf780-4e95-11eb-9850-0039249a4ae3.png)
@barnstee Please find the path screenshots ,directory mapping is that same you are talking about....

**Comment by barnstee** [comment]
"Binds" in your case should be ["/app:/app"], as you placed your publishesnodes.json in the /app folder on both the host and the container.

**Comment by sagarganachari** [comment]
I copied the host file inside container and checked the same .but still i get heartbeat model error.find attached screen shots

to copy the host publishenodes.json file to container   /iiotedge/ location i used the command.

$ tar -cv * | docker exec -i OPCPublisher tar x -C /

Is it right to copy ?? after copy i can  access the file inside container.




![image](https://user-images.githubusercontent.com/76048188/103625074-55b7cc80-4f32-11eb-9e93-0f5c6cf42133.png)
![image](https://
![image](https://user-images.githubusercontent.com/76048188/103625241-9ca5c200-4f32-11eb-851e-ee75cec1297b.png)
user-images.githubusercontent.com/76048188/103625146-7849e580-4f32-11eb-8160-a989a75452d1.png

**Comment by barnstee** [comment]
No, copying is not the right solution as the file will be gone when the container restarts. You need to map it as @franperezlopez and I described above. Please read up on principles of Docker containers to get an overview of how they work.

**Comment by sagarganachari** [comment]
> No, copying is not the right solution as the file will be gone when the container restarts. You need to map it as @franperezlopez and I described above. Please read up on principles of Docker containers to get an overview of how they work.
![image](https://user-images.githubusercontent.com/76048188/103639928-0def7000-4f47-11eb-9391-c56c35d92f28.png)

@barnstee  After inspecting the container i can see that volume is mounted on the container,,,,,,but still result remains same
![image](https://user-images.githubusercontent.com/76048188/103640126-632b8180-4f47-11eb-91ad-9912e7ef7ed4.png)

that i cannot access the file with ls /iiotedge/publishenodes.json......
