### ISSUE TITLE
Error: There is no PublishedNodes.json

### ISSUE THREAD

**Issue by PedroFloresGuillen** [Azure/iot-edge-opc-publisher#29]
I followed the building module, and when i was going to configure it, I found there was no publishedNodes.json neither in the proyect nor the folder.

When I was restoring, those warmings appeared

![opc ua module](https://cloud.githubusercontent.com/assets/28599539/25902469/e2b29c48-3599-11e7-9761-1d2084c4aaff.png)

I published it without problems.

My dotnet --version
1.0.0-preview2-003131

So, maybe the fault is in the publish part?

**Comment by PedroFloresGuillen** [comment]
Nevermind, I created the file and it solved the problem.

**Comment by barnstee** [comment]
No error. The publishednodes.json file is *automatically generated and persisted to disk* as soon as you call the OPC UA server interface built-in to the publisher (publishnode method). You can of course create one yourself manually, if you want.

**Comment by rish11** [comment]
@PedroFloresGuillen where did you created that file ?

**Comment by PedroFloresGuillen** [comment]
To manually create the file, I used Visual Studio to create a Json file named publishednodes in GatewayApp.NetCore

**Comment by rish11** [comment]
@PedroFloresGuillen  I am new to VS can you guide me step by step on how to configure the module ?

**Comment by PedroFloresGuillen** [comment]
Of course, in order to have a publishednodes.json you should do these steps.
![new element](https://cloud.githubusercontent.com/assets/28599539/26773742/e68d99ca-49cc-11e7-9cf3-69bd339f0ad3.png)

![net core](https://cloud.githubusercontent.com/assets/28599539/26773744/e69a7d3e-49cc-11e7-9a9b-870e4f2f9399.png)

![nodes](https://cloud.githubusercontent.com/assets/28599539/26773743/e68f5788-49cc-11e7-83d4-790369e7f9fb.png)

**Comment by rish11** [comment]
@PedroFloresGuillen I have already done this. I'm asking steps for Configuring the gateway

**Comment by PedroFloresGuillen** [comment]
You should explain more what do you want. But, if you mean passing the args, you have 2 args to pass.
Aplication Name: This can be wathever you want, it will be the name of the gateway.
Iot Hub address: This is the address of the hub you want to link the gateway.

![configuration](https://cloud.githubusercontent.com/assets/28599539/26775103/b41513e0-49d3-11e7-8d84-40a75fb73fea.png)

**Comment by rish11** [comment]
@PedroFloresGuillen  ohk 
so what should be the IoT hub address? Should I take it from azure portal ? Is it the connecting String ?

**Comment by PedroFloresGuillen** [comment]
Yes, the conection String from azure of the IoT hub you want to use.

**Comment by rish11** [comment]
I have passed the arguments. And now when I'm running it, It's showing dll file missing error
![error](https://cloud.githubusercontent.com/assets/29191744/26776240/ed61e968-49c7-11e7-85c6-9b12e68b2083.PNG)

**Comment by PedroFloresGuillen** [comment]
![comando build iot edge](https://cloud.githubusercontent.com/assets/28599539/26776556/daa33086-49d9-11e7-8ef5-3f6b54eb9b65.png)

Did you build edge this way? Also, what version do you have of the publisher and gateway?

**Comment by rish11** [comment]
No I didn't build it this way,I have just press F5 to run 
I have the latest version of both

**Comment by PedroFloresGuillen** [comment]
When you build the gateway, you should build it with --enable-dotnet-binding, or the module wont work.

**Comment by rish11** [comment]
but there isn't any tool folder in iot-edge-opc-publisher
C:\Users\rishabhgupta_pwc\Desktop\OPCCLIENT> 
This is the directory where all the files are. what i have to do next ?

**Comment by PedroFloresGuillen** [comment]
iot-edge-opc-publisher is a module for Iot-edge. you have to clone iot edge, build it with the options, and then you will be able to use the module.

**Comment by rish11** [comment]
I have done as yous aid while building I got these two errors. 
![error1](https://cloud.githubusercontent.com/assets/29191744/26779088/8f4c9cc2-49d3-11e7-9159-a0b1d7daa6d4.PNG)
![error2](https://cloud.githubusercontent.com/assets/29191744/26779087/8f4b5cc2-49d3-11e7-966e-369c2db19323.PNG)

**Comment by PedroFloresGuillen** [comment]
Delete iot edge master folder
do: git clone https://github.com/Azure/iot-edge.git
do: cd: iot-edge/tools
do: build.cmd --enable-dotnet-binding

**Comment by rish11** [comment]
same error is showing

**Comment by PedroFloresGuillen** [comment]
well, i dont know why it happens then, never happened to me, you should open a new issue and try your luck there.

**Comment by rish11** [comment]
@PedroFloresGuillen  
Hey, My problem has been solved. 
I the project is running and I have connected it to IoT Hub. MY OPC Server is active but I can't see the data. Where should I see it ?

**Comment by PedroFloresGuillen** [comment]
That is what im working right on, if I manage to make something viable I will tell you.

**Comment by barnstee** [comment]
IMPORTANT: You don't need to clone IoT-Edge. We have NuGet packages for IoT-Edge now.

**Comment by rish11** [comment]
yup.
My iot-edge-opc-publisher is working. 
But now the problem how should I read the data from OPC client ? 
Also from where you have taken the Mock OPC server please tell me it will be really helpfull.

**Comment by PedroFloresGuillen** [comment]
https://github.com/OPCFoundation/UA-.NETStandardLibrary (here is where i got the mock server)

To see data from a server, you can use a client that connects to it, like UAExpert

**Comment by rish11** [comment]
Then how are you visualizing the data in IoT hub ? 
And I have endpoint url of an active server and I have put it in PublishedNodes.json 
But I dont know how to see the tags in IoT Hub..

**Comment by PedroFloresGuillen** [comment]
Oh, currently im not visualizing the data in IoT hub, its what im looking too.

**Comment by barnstee** [comment]
https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer

**Comment by barnstee** [comment]
Simple website for telemetry: https://github.com/OPCFoundation/UA-.NETStandardLibrary/tree/master/OpcUaWebTelemetry

**Comment by barnstee** [comment]
Full connected factory preconfigured solution using Publisher: www.azureiotsuite.com

**Comment by f17jwr** [comment]
@rish11 I am still having issues even after building iot-edge, as you did - how did you overcome this?
it just says my runtime folders are not found
