### ISSUE TITLE
Is there any format available to send Status Code with message?

### ISSUE THREAD

**Issue by subbu-ai** [Azure/iot-edge-opc-publisher#296]
I am using OPC Pub/Sub format which sends the Status Code only when status is bad.  Is there any other format available for selection as --mm parameter to send the Status Code with every message; both good and bad?

**Comment by monikavar** [comment]
We don't support this currently.

**Comment by subbu-ai** [comment]
Is there any option available to STOP the "Bad" messages from being sent to IoTHub?
