### ISSUE TITLE
How to send 2 sec and 5 sec frequency messages to cloud?

### ISSUE THREAD

**Issue by subbu-ai** [Azure/iot-edge-opc-publisher#297]
I have 2 sec and 5 sec messages.  At source OPC/UA Tunnel, we are polling at an interval of 3 sec.  The messages are going to cloud at 10 sec interval and 1 sample is missed.  How to ensure all samples reach cloud at the same source frequency as 5 sec?

**Comment by barnstee** [comment]
Have a look here: https://github.com/Azure/iot-edge-opc-publisher#performance-and-memory-tuning-opc-publisher
You need to tune the si /ms parameter.
