### ISSUE TITLE
OPC Publisher 2.7.199 + IoT EdgeHub Dev Error: System.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by Prov-Matthias** [Azure/iot-edge-opc-publisher#299]
When we running docker container mcr.microsoft.com/iotedge/opc-publisher:2.7.199 as a module inside IoT Edge Hub Dev runtime the following error occurs:

`Unhandled exception. System.AggregateException: One or more errors occurred. (An exception was thrown while activating Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost -> Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.)
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost -> Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.`

Same issue with other Publisher container versions 2.6.x & 2.5.x (with some of this container we have tested). 
**With version 2.3.3 as descripted in issue [#268 ](https://github.com/Azure/iot-edge-opc-publisher/issues/268) the Publisher is running.**

Therefore please consider the issue maybe as info ;)

Development environment:

- Azure VM Win10 (1809)
- Visual Studio 2019
- Azure IoT Edge Tools for VS 2019

OPC Publisher configuration:
```
"publisher": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/iotedge/opc-publisher:2.7.199-nanoserver-amd64-1809",
              "createOptions": {
                "User": "ContainerAdministrator",
                "Hostname": "publisher",
                "Cmd": [
                  "publisher",
                  "--pf=C:/mount/pn.json",
                  "--lf=C:/mount/debug.log",
                  "--aa"
                ],
                "HostConfig": {
                  "PortBindings": {
                    "62222/tcp": [
                      {
                        "HostPort": "62222"
                      }
                    ]
                  },
                  "Binds": [
                    "c:/edge_opcua:C:/mount"
                  ],
                  "ExtraHosts": [
                    "localhost:127.0.0.1"
                  ]
                }
              }
            }
          }
```
Publisher configuration (publishednodes.json):
```
[
  {
    "EndpointUrl": "opc.tcp://server.domain.com:4811/P1/ABC123",
    "OpcNodes": [
      {
        "Id": "ns=28;s=SPS_I.bLebenszeichen",
        "OpcSamplingInterval": 10,
        "OpcPublishingInterval": 100
      },
      {
        "Id": "ns=28;s=SPS_I.bAutomatikbetrieb_aktiv",
        "OpcSamplingInterval": 10,
        "OpcPublishingInterval": 100
      },
      {
        "Id": "ns=28;s=SPS_I.strRezeptname",
        "OpcSamplingInterval": 10,
        "OpcPublishingInterval": 100
      },
      {
        "Id": "ns=28;s=SPS_I.diStueckzaehler",
        "OpcSamplingInterval": 10,
        "OpcPublishingInterval": 100
      }
    ]
  }
]
```

Complete error (stack trace):
[IoTEdgeHubDev-OPCPublisher-Error.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5885578/IoTEdgeHubDev-OPCPublisher-Error.txt)

**Comment by barnstee** [comment]
Thanks Matthias, as discussed on the phone, edgehub dev environment is not supported.
