### ISSUE TITLE
Cryptic string in json-file

### ISSUE THREAD

**Issue by fijo1015** [Azure/iot-edge-opc-publisher#301]
Hi,

i am using OPC Publisher in combination with the message routing of the IoT Hub. I want to store the incoming messages in a json-file (Blob Storage). When i am doing this, the body of the file is a cryptic string. When i am storing the incoming messages in an avro-file, it works very well. Can anybody tell me, what is the reason for that behavior? What can I do to "see" the data in the json-file as well?

I am using OPC Publisher v.2.5.3.

Best regards
jo
![image](https://user-images.githubusercontent.com/73999251/107774506-60d6f700-6d3f-11eb-9d63-e0e38a7e0246.png)

**Comment by fijo1015** [comment]
It´s the issue #267. I am closing this issue.

**Comment by faroqahmd** [comment]
cryptic message is apparently base64 encoded data. You can use an online base64 to text decoders to observe data
