### ISSUE TITLE
Curiosity about PublisherModel.xml and Publisher.PredefinedNodes.uanodes files in a Ua.Publisher Module

### ISSUE THREAD

**Issue by JayeshThamke** [Azure/iot-edge-opc-publisher#31]
Hello,
I am much curious about how do you create 
`PublisherModel.xml`  
file to create new ObjectType and Method nodes. Is there any tool, is it available as open source? I am asking this because I want to change (may be add) the methods or args for my customized application. Thanks.

Also, what is Publisher.PredefinedNodes.uanodes file? How did you create this file? Thanks

**Comment by barnstee** [comment]
https://github.com/OPCFoundation/UA-ModelCompiler
