### ISSUE TITLE
Add new modules for solution

### ISSUE THREAD

**Issue by dackienngo** [Azure/iot-edge-opc-publisher#35]
Hi Everyone

I am trying create modules same Opc.Ua.Publisher.Module project, below is code in gatewayconfig.json file. 
{
  "modules": [
    {
      "name": "OpcUa",
      "loader": {
        "name": "dotnetcore",
        "entrypoint": {
          "assembly.name": "Opc.Ua.Publisher.Module",
          "entry.type": "Opc.Ua.Publisher.Module"
        }
      },
      "args": {
        "Configuration": {
          "ApplicationName": "iov",
          "ApplicationType": "ClientAndServer",
          "ApplicationUri": "urn:localhost:microsoft:publisher"
        }
      }
    },
    {
      "name": "IoTHub",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "iothub.dll"
        }
      },
      "args": {
        "IoTHubName": "iov",
        "IoTHubSuffix": "azure-devices.net",
        "Transport": "MQTT"
      }
    },
    {
      "name": "IoTDevices",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "IoTDevices.dll"
        }
      },
      "args": {
        "IoTHubName": "iov",
        "IoTHubSuffix": "azure-devices.net",
        "Transport": "MQTT"
      }
    }
  ],
  "links": [
    {
      "source": "OpcUa",
      "sink": "IoTHub"
    }
  ]
}
But when i run GatewayApp.NetCore project, so show error "returned null is IoTDevices.dll"
Please everyone support add new moudule into solution

Thank so much
Kien

**Comment by barnstee** [comment]
Please log this issue here: https://github.com/Azure/iot-edge/issues
