### ISSUE TITLE
Opc Publisher endpoint wont be found by its name

### ISSUE THREAD

**Issue by PedroFloresGuillen** [Azure/iot-edge-opc-publisher#38]
I have IoT Edge up and running with the module of OPC, but when I try to get to the endpoint of the server using a client (opc.tcp://<name>:62222/UA/Publisher) it wont find it. But when I connect to opc.tcp://localhost:62222/UA/Publisher it will appear without problems, being able to connect to it.

![gateway](https://cloud.githubusercontent.com/assets/28599539/26822337/f8a832d6-4aa9-11e7-854a-702647af41c0.png)

**Comment by barnstee** [comment]
opc.tcp://:62222/UA/Publisher is not a valid URL. This issue appear to be related to UA Expert, please check with Unified Automation if they are able to parse this type of URL.

**Comment by PedroFloresGuillen** [comment]
Sorry, i meant opc.tcp://Gateway:62222/UA/Publisher

**Comment by barnstee** [comment]
Do you have a hosts file entry for "Gateway" on your system. What happens when you call "ping Gateway" from command prompt?

**Comment by PedroFloresGuillen** [comment]
Oh, haven't thought of that, added it and now it works appropiately, sincerely thanks you.

**Comment by barnstee** [comment]
not a problem, no.
