### ISSUE TITLE
Need to build a Windows Docker container - The current Dockerfile only builds a Linux Docker Container

### ISSUE THREAD

**Issue by faister** [Azure/iot-edge-opc-publisher#45]
Reason for building a Windows Docker container - if Docker daemon runs on Windows Sever 2016, one can only run a Windows-based Docker container. 

So I changed the Dockerfile as follows:
FROM microsoft/dotnet:1.1.2-sdk-nanoserver

COPY / /build

WORKDIR /build
RUN dotnet restore

WORKDIR /build/src/GatewayApp.NetCore
RUN dotnet publish -c Release -f netcoreapp1.1 -r win10-x64 -o bin/Debug/netcoreapp1.1

WORKDIR /build/src/GatewayApp.NetCore/bin/Debug/netcoreapp1.1
ENV PATH=/build/src/GatewayApp.NetCore/bin/Debug/netcoreapp1.1/runtimes/win-x64/native;/build/src/GatewayApp.NetCore/bin/Debug/netcoreapp1.1/
ENTRYPOINT ["./GatewayApp.NetCore"]

**Comment by barnstee** [comment]
I never tried running a Windows native Docker container. Once you get it working, please send a pull request and call the native Windows container Docker-file dockerfile.windows!
