### ISSUE TITLE
Could not send an open secure channel request

### ISSUE THREAD

**Issue by carlwouters** [Azure/iot-edge-opc-publisher#53]
Specifications:
- Windows PC
- Kepware OPC UA sample server
- Certificates should be ok (after issues with SHA1 certificates)

When trying to get the OPC UA publisher working, we are getting an error:

12:13:55.647 ***EXCEPTION*** BadTcpInternalError 'Could not send an Open Secure Channel request.'
12:13:55.651 ***EXCEPTION*** BadTcpInternalError 'Error establishing a connection: Could not send an Open Secure Channel request.'

I’ve added the log file:

[DigitalTwinTest.log.txt](https://github.com/Azure/iot-edge-opc-publisher/files/1138089/DigitalTwinTest.log.txt)

**Comment by PedroFloresGuillen** [comment]
Have you tried using the .net sample server?

**Comment by carlwouters** [comment]
When trying to connect to the sample server with UAExpert, I get this error:

![image](https://user-images.githubusercontent.com/86311/28104781-ff414d0e-66dc-11e7-9492-93ebaa2d22af.png)

The UAExpert certificate is in the UA Application certs folder. (not in the rejected anymore)

**Comment by carlwouters** [comment]
Seems that the certificate made by the iot edge publisher was a protected one with a key. Removing that solved the issue.
