### ISSUE TITLE
cannot find Runtimes folder

### ISSUE THREAD

**Issue by f17jwr** [Azure/iot-edge-opc-publisher#57]
![unbenannt](https://user-images.githubusercontent.com/30241535/28328064-8933843e-6be5-11e7-97df-e177a3485353.PNG)

I am having issues resolving this problem, any help would be greatly appreciated.

**Comment by f17jwr** [comment]
Upon further digging I have realised that a 'runtimes' folder is missing from my GatewayApp.NetCore folder and I am unsure why.

**Comment by barnstee** [comment]
Can you use the latest code from master? GatewayApp.NetCore is now no longer needed.

**Comment by f17jwr** [comment]
What code do you mean?

**Comment by barnstee** [comment]
The publisher code.

**Comment by f17jwr** [comment]
That still isn't helpful.

**Comment by barnstee** [comment]
Please sync to the latest Publisher code in the master branch, i.e. git pull from master branch. You will see that  GatewayApp.NetCore has been removed as it is no longer needed, along with the code to find the runtimes folder.

**Comment by f17jwr** [comment]
Ah ok thankyou.
