### ISSUE TITLE
Orphaned messages are received in IoTHub

### ISSUE THREAD

**Issue by JayeshThamke** [Azure/iot-edge-opc-publisher#63]
In IoTHub, I have started receiving messages to IoTHub via AMQP telemetry and UaJSON format. However, I have found these messages are Orphaned Messages and hence I cannot create a Blob Storage using Stream Analytics job.

Did anybody came cross this issue earlier?
Is there any configuration items or properties need to be changed?

Thanks for reply,
Jayesh

![orphaned_messages](https://user-images.githubusercontent.com/28365503/28874859-deee5a8e-7793-11e7-9d8a-a36852a1bfc9.png)

**Comment by JayeshThamke** [comment]
I have corrected message routing and it works.

**Comment by marwaadihu** [comment]
Hey Jayesh, Can you please tell what you corrected in message routing, in my case it is correct routing as per requirement, although I am getting this issue
