### ISSUE TITLE
Cannot reconnect to OPCUA server

### ISSUE THREAD

**Issue by zhironghsu** [Azure/iot-edge-opc-publisher#71]
Hi,

I run the publisher and get the following message when the OPCUA server is down, then I restart the OPCUA server, the publisher cannot reconnect to the server.

Status: BadNoCommunication 'Server not responding to keep alive requests.'/t/tOutstanding requests: 0/t/tDefunct requests
: 0

**Comment by hansgschossmann** [comment]
Interesting, I will give it also a try over the next few days.

**Comment by carlwouters** [comment]
Just updated to latest version and getting similar errors from time to time which causes app to shutdown. Error message in attachment.
[error.txt](https://github.com/Azure/iot-edge-opc-publisher/files/1251825/error.txt)

Shouldn't the app need to try to reconnect?

**Comment by hansgschossmann** [comment]
yeah, i will send a pull request out after i return from vacation on the 9/4.
if one would like you folks could check out my for which has all the changes at https://github.com/hansgschossmann/iot-edge-opc-publisher.git

**Comment by zhironghsu** [comment]
There is batching message in the code. 
Why not use DeviceClient.SendEventBatchAsync() directly? If I am misunderstanding something?

**Comment by hansgschossmann** [comment]
The implementation we have in the code base is independent from the transport. SendEventBatchAsync is right now only implemented in Http. Mqtt for example just sends each message as a single message to IoTHub. Hope this answers your question.

**Comment by hansgschossmann** [comment]
@zhironghsu: v2.1.0 implements a different server connection strategy. please open a new issue if you still see problems.
