### ISSUE TITLE
Data timestamps running away

### ISSUE THREAD

**Issue by carlwouters** [Azure/iot-edge-opc-publisher#82]
We have been testing the latest commits.
Our nodes are in the format:

{
                "ExpandedNodeId": "nsu=http://opcfoundation.org/UA/;i=1",
                "OpcSamplingInterval": 1000
}
{
                "ExpandedNodeId": "nsu=http://opcfoundation.org/UA/;i=2",
                "OpcSamplingInterval": 1000
}
{
                "ExpandedNodeId": "nsu=http://opcfoundation.org/UA/;i=3",
                "OpcSamplingInterval": 30000
}
{
                "ExpandedNodeId": "nsu=http://opcfoundation.org/UA/;i=4",
                "OpcSamplingInterval": 30000
}

All sensor data is sampled at 30s while run cmds etc.. at 1s. (In total more than 300 data points at the moment)
We see that the actual timestamp of the sensor data is creeping away from the timestamp IoT Hub receives the messages:

![image](https://user-images.githubusercontent.com/86311/30803211-1ac2ba4e-a1e9-11e7-806f-3073019cae5d.png)

Are we missing something?

**Comment by hansgschossmann** [comment]
i will look into this in more detail in the next weeks. since we support now batching of the messages to IoTHub, could you first do a restest by disabling batching via commandline parameters. The iothub-enqueue timestamp includes also network latency and is non determenistic. The order of the messages should be preserved at least.

**Comment by carlwouters** [comment]
How can I disable batching?
I've put --ms at 0, but no difference.

Maybe as additional information, it seems the edge application is only publishing at 30s, but due to the amount of nodes, it can't publish them all together so it queue's them up for next publish interval?

![image](https://user-images.githubusercontent.com/86311/31880607-55711bfa-b7e1-11e7-915d-89428f208aad.png)

**Comment by hansgschossmann** [comment]
with --ms 0 it will send each 1 sec interval. with an additional --si 0, it will send each message. i will look into that in the next few weeks.

**Comment by carlwouters** [comment]
It seems that because I put sampling interval at 30s, it will only send messages to Hub each 30s even though it can't send all messages in one time.

**Comment by hansgschossmann** [comment]
hi carl, please update the issue with your latest findings and let me know if there are still issues.

**Comment by carlwouters** [comment]
Solution:
- Update namespace tags (ns to nsu)
- Update to version 2.1.1 solved all latency issues

Everything is now running smoothly.
