### ISSUE TITLE
Error "Predefined type 'System.xxxxxxx' is not defined or imported"

### ISSUE THREAD

**Issue by qwertyzq** [Azure/iot-edge-opc-publisher#83]
I am error when i download your code and run it in visual studio
it say have error around 1xxx error like this

![error](https://user-images.githubusercontent.com/32866940/31658487-54c619f6-b35b-11e7-9e0a-14bcbafc3892.jpg)

"Predefined type 'System.Boolean' is not defined or imported"
"Predefined type 'System.Byte' is not defined or imported"
"Predefined type 'System.Double' is not defined or imported"
"Predefined type 'System.xxxxxxx' is not defined or imported"
Etc. 

I don't know why? how can i fix it?
thank you and best regards.

**Comment by barnstee** [comment]
Please verify that you have installed the .NetCore 2.0 SDK.

**Comment by carlwouters** [comment]
Also take care you have the latest VS update to take care .NetCore 2.0 works.

**Comment by qwertyzq** [comment]
I already install .NetCore 2.0 SDK From [https://www.microsoft.com/net/download/core](url) 

but it still error.

**Comment by qwertyzq** [comment]
I already install .NetCore 2.0 SDK from [https://www.microsoft.com/net/download/core#/sdk](url)
but it still error.

**Comment by hansgschossmann** [comment]
Have you tried to run a dotnet restore src/OpcPublisher.sln? You need to ensure that your nuget is configured correctly.

**Comment by hansgschossmann** [comment]
@qwertyzq: have nothing heard back for a while. closing it now. please open a new one if you still see issues.
