### ISSUE TITLE
publisher could be accidently terminated

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-publisher#86]
Hello,

for productive usage the publisher is expected to run permanently.
But the publisher reads from standard input:
https://github.com/hansgschossmann/iot-edge-opc-publisher/blob/a43e00e6a6b2d3d23fe884981ec734380acf3b12/src/Program.cs#L479
So the publisher terminates, if someone gives accidentally a key stroke to the terminal running the publisher.
If trying to start the publisher in some daemon like mode from an init script, it terminates immediately after initialization due to the lack of standard input.

**Comment by hansgschossmann** [comment]
I see your point. A "detached terminal" mode would make sense to add.

**Comment by barnstee** [comment]
The NetCoreConsoleServer implements this, have a look at:
https://github.com/OPCFoundation/UA-.NETStandardLibrary/blob/master/SampleApplications/Samples/NetCoreConsoleServer/Program.cs

**Comment by hansgschossmann** [comment]
i will address this in the next release

**Comment by JuergenKosel** [comment]
Fixed in https://github.com/Azure/iot-edge-opc-publisher/tree/2.1.2
